name: lint

on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run all pre-commit checks
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            test_requirements.txt

      - run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt -r test_requirements.txt

      - uses: pre-commit/action@v3.0.0
